apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-test-app-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-test-app-1
  template:
    metadata:
      labels:
        app: kubernetes-test-app-1
    spec:
      containers:
      - name: kubernetes-test-app-1
        image: kubernetes-test-app-1:v1
        imagePullPolicy: Never
        resources:
          limits:
            memory: "64Mi"
            cpu: "200m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-test-app-1
spec:
  type: NodePort
  selector:
    app: kubernetes-test-app-1
  ports:
  - port: 8080
    targetPort: 5000
    nodePort: 30007
